In [18]:
import torch
from torch import nn
m = nn.Dropout(p=0.5)
input = torch.randn(1, 5, 5)
output = m(input)
output

# Dropout.cpp源码
# if (p == 0 || !train || input.numel() == 0) {
#     return input;
#   }

tensor([[[ 4.8833,  0.0000,  0.4930, -0.0000,  0.5939],
         [-0.0000,  0.0000, -1.8928,  0.0000,  0.0000],
         [ 1.9358, -3.5015,  0.0000, -0.0000,  0.0000],
         [ 0.0000, -3.1049, -0.0000, -0.7500, -0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.8176,  0.9292]]])

In [15]:
m = nn.BatchNorm2d(2)
input = torch.randn(1, 2, 3, 4)
output = m(input)
output

tensor([[[[-2.3866,  0.7801,  1.3211, -0.0594],
          [ 0.1229, -0.3531,  0.6838,  1.1586],
          [-0.8050, -0.0357, -1.0059,  0.5793]],

         [[-0.6803, -0.5501,  0.6612, -0.0157],
          [ 1.1221,  0.5020,  0.2969, -1.3084],
          [ 2.2809, -0.5808, -0.3878, -1.3400]]]],
       grad_fn=<NativeBatchNormBackward>)

In [7]:
import numpy as np
X = np.array(([1,2],[3,3],[5,7],[3,1],[6,1]))
X

array([[1, 2],
       [3, 3],
       [5, 7],
       [3, 1],
       [6, 1]])

In [ ]:
y = np.array([[],[],[],[],[]])
# y = 6 * x1 + 4 * x2 + 6