### Pytorch教程：Linear Regression的numpy实现

In [43]:
import numpy as np
np.random.seed(0)
X = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [6, 9]])
y = np.array([[8], [12], [16], [20], [25]])
# y = 2 * x1 + x2 + 4

w = np.random.rand(2, 1)
w

array([[0.5488135 ],
       [0.71518937]])

In [44]:
b = np.random.rand(1,1)
b

array([[0.60276338]])

In [45]:
iter_count = 10000
lr = 0.002

In [46]:
def forword(x):
    return np.matmul(x, w) + b

In [47]:
def loss(y, y_pred):
    return ((y - y_pred) ** 2 / 2).sum()

In [48]:
def gradient(x, y, y_pred):
    return np.matmul(x.T, y_pred - y)

In [49]:
for i in range(iter_count):
    y_pred = forword(X)
    l = loss(y, y_pred)
    print(f'iter {i}, loss {l}')
    grad_w = gradient(X, y, y_pred)
    grad_b = gradient(np.ones(y.shape), y, y_pred)
    w -= lr * grad_w
    b -= lr * grad_b

iter 0, loss 260.55901241115583
iter 1, loss 57.849586783302485
iter 2, loss 14.993264211514397
iter 3, loss 5.926066530472492
iter 4, loss 4.0011086574755375
iter 5, loss 3.5858815195504907
iter 6, loss 3.4898083659555503
iter 7, loss 3.461229821386831
iter 8, loss 3.446951002329224
iter 9, loss 3.4357276336602944
iter 10, loss 3.425182788068283
iter 11, loss 3.414813882571754
iter 12, loss 3.404514526217305
iter 13, loss 3.394262074324309
iter 14, loss 3.384051584982354
iter 15, loss 3.373881859042943
iter 16, loss 3.36375248930584
iter 17, loss 3.3536632367837327
iter 18, loss 3.3436138988551565
iter 19, loss 3.333604281390741
iter 20, loss 3.3236341928569613
iter 21, loss 3.313703443065399
iter 22, loss 3.3038118429040093
iter 23, loss 3.2939592042759513
iter 24, loss 3.284145340082341
iter 25, loss 3.2743700642143017
iter 26, loss 3.2646331915469924
iter 27, loss 3.2549345379341195
iter 28, loss 3.245273920202521
iter 29, loss 3.2356511561468335
iter 30, loss 3.226066064524162
ite

In [50]:
lr * gradient(np.ones(y.shape), y, np.ones(y.shape))
b - lr * gradient(np.ones(y.shape), y, np.ones(y.shape))

array([[4.15181873]])

In [51]:
w

array([[1.99987666],
       [1.00009633]])

In [52]:
b

array([[3.99981873]])

In [56]:
forword(np.array([[10, 2], [100, 100]]))

array([[ 25.99877804],
       [303.99711839]])