### Pytorch教程：Linear Regression的Autograd实现

In [8]:
import numpy as np
np.random.seed(0)
X = np.array([[1, 2], [2, 4], [3, 6], [4, 8], [6, 9]])
y = np.array([[8], [12], [16], [20], [25]])
# y = 2 * x1 + x2 + 4

w = np.random.rand(2, 1)
w

(tensor([[1., 2.],
         [2., 4.],
         [3., 6.],
         [4., 8.],
         [6., 9.]]), tensor([[ 8.],
         [12.],
         [16.],
         [20.],
         [25.]]))

In [9]:
w = torch.rand(2, 1, requires_grad=True, dtype=torch.float32)
w

tensor([[0.0825],
        [0.7606]], requires_grad=True)

In [10]:
b = np.random.rand(1,1)
b

tensor([[0.2786]], requires_grad=True)

In [11]:
iter_count = 10000
lr = 0.002

In [12]:
def forword(x):
    return torch.matmul(x, w) + b

In [13]:
def loss(y, y_pred):
    return ((y - y_pred) ** 2 / 2).sum()

In [14]:
for i in range(iter_count):
    y_pred = forword(X)
    l = loss(y, y_pred)
    print(f'iter {i}, loss {l}')
    
    l.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        w.grad.zero_()
        b.grad.zero_()
        

iter 0, loss 354.0401611328125
iter 1, loss 78.08636474609375
iter 2, loss 19.747676849365234
iter 3, loss 7.407616138458252
iter 4, loss 4.790588855743408
iter 5, loss 4.22880220413208
iter 6, loss 4.101471424102783
iter 7, loss 4.066008567810059
iter 8, loss 4.049994945526123
iter 9, loss 4.038121223449707
iter 10, loss 4.027150630950928
iter 11, loss 4.016400337219238
iter 12, loss 4.005729675292969
iter 13, loss 3.9951021671295166
iter 14, loss 3.9845125675201416
iter 15, loss 3.973961591720581
iter 16, loss 3.963446855545044
iter 17, loss 3.952970266342163
iter 18, loss 3.942528247833252
iter 19, loss 3.932121515274048
iter 20, loss 3.92175555229187
iter 21, loss 3.9114229679107666
iter 22, loss 3.901123046875
iter 23, loss 3.890861988067627
iter 24, loss 3.8806371688842773
iter 25, loss 3.8704473972320557
iter 26, loss 3.860290765762329
iter 27, loss 3.850170135498047
iter 28, loss 3.8400840759277344
iter 29, loss 3.8300342559814453
iter 30, loss 3.820016622543335
iter 31, loss 3

In [15]:
w

tensor([[1.9999],
        [1.0001]], requires_grad=True)

In [16]:
b

tensor([[3.9998]], requires_grad=True)

In [21]:
forword(torch.tensor([[10, 2], [22, 5]], dtype=torch.float32))

tensor([[25.9985],
        [52.9971]], grad_fn=<AddBackward0>)