### 1. Array

In [1]:

import numpy as np
a = np.array([1,2,3], dtype = int, order = 'F', ndmin = 2)
print(a)
b = np.array([[1,  2],  [3,  4]])
print(b)

(1, 3)
[[1 2 3]]
[[1 2]
 [3 4]]


### 2. 创建数组，默认为浮点型
- numpy.empty
- numpy.zeros
- numpy.ones

In [ ]:
x = np.empty([3,2]) 
print (x)
x = np.zeros([3,2]) 
print (x)
x = np.ones([3,2]) 
print (x)

### 3. 从已有数据中创建数组
- numpy.asarray(dtype：数据类型，可选。order：可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。)
- numpy.frombuffer(dtype:返回数组的数据类型; count:读取的数据数量，默认为-1，读取所有数据 )

In [12]:
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[(1, 2, 3) (4, 5)]
[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


### 4. 从数值范围创建数组
- numpy.arange(start, stop, step, dtype)
- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- numpy.logspace 函数用于创建一个于等比数列。np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [15]:
x = np.arange(5)  
print (x)
x = np.arange(1,5)  
print (x)
x = np.arange(1,5,2)  
print (x)

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [18]:
a = np.logspace(0,10,10,endpoint=False,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


### 5. 切片和索引

In [23]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]
[2 4 6]


In [26]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


### 6. 数组操作
- numpy.reshape
- numpy.ndarray.flat
- numpy.ndarray.flatten
- numpy.ravel